[package]
name = "repl"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
parser = { path = "../parser" }
lexer = { path = "../lexer" }
diag = { path = "../diag" }
colored = "1.7.0"
linefeed = "0.5.4"

[dev-dependencies]
rand = "0.6.5"
